Kora Today/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kora_Today.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace Kora_Today.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ClubController : Controller
    {
        private KoraTodayEntities db = new KoraTodayEntities();

        //
        // GET: /Club/

        public ActionResult Index(int? page, string sortby)
        {
            ViewBag.league = string.IsNullOrEmpty(sortby) ? "league desc" : "";
            var clubs = db.Clubs.AsQueryable();
            switch (sortby)
            {
                case "league desc":
                    clubs = clubs.OrderByDescending(x => x.League.LeagueName);
                    break;
                default:
                    clubs = clubs.OrderBy(x => x.League.LeagueName);
                    break;

            }
            return View(clubs.ToPagedList(page ?? 1, 6));
        }

        //
        // GET: /Club/Create

        public ActionResult Create()
        {
            ViewBag.LeagueId = new SelectList(db.Leagues, "LeagueId", "LeagueName");
            return View();
        }

        //
        // POST: /Club/Create

        [HttpPost]
        public ActionResult Create(Club club, HttpPostedFileBase ClubPhoto)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), ClubPhoto.FileName);
                ClubPhoto.SaveAs(path);
                club.ClubImage = ClubPhoto.FileName;
                db.Clubs.Add(club);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ModelState.Clear();
            ViewBag.LeagueId = new SelectList(db.Leagues, "LeagueId", "LeagueName", club.LeagueId);
            return View(club);
        }

        //
        // GET: /Club/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeagueId = new SelectList(db.Leagues, "LeagueId", "LeagueName", club.LeagueId);
            return View(club);
        }

        //
        // POST: /Club/Edit/5

        [HttpPost]
        public ActionResult Edit(Club club)
        {
            if (ModelState.IsValid)
            {
                db.Entry(club).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeagueId = new SelectList(db.Leagues, "LeagueId", "LeagueName", club.LeagueId);
            return View(club);
        }

        //
        // GET: /Club/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return HttpNotFound();
            }
            return View(club);
        }

        //
        // POST: /Club/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Club club = db.Clubs.Find(id);
            db.Clubs.Remove(club);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kora Today/Controllers/LeagueController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kora_Today.Models;
using System.IO;

namespace Kora_Today.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LeagueController : Controller
    {
        private KoraTodayEntities db = new KoraTodayEntities();
        //
        // GET: /League/

        public ActionResult Index()
        {
            return View(db.Leagues.ToList());
        }

        //
        // GET: /League/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /League/Create

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(League league, HttpPostedFileBase LeaguePhoto)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), LeaguePhoto.FileName);
                LeaguePhoto.SaveAs(path);
                league.LeagueImage = LeaguePhoto.FileName;
                db.Leagues.Add(league);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ModelState.Clear();
            return View(league);
        }

        //
        // GET: /League/Edit/5

        public ActionResult Edit(int id = 0)
        {
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }
            return View(league);
        }

        //
        // POST: /League/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(League league,HttpPostedFileBase LeaguePhoto)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), LeaguePhoto.FileName);
                LeaguePhoto.SaveAs(path);
                league.LeagueImage = LeaguePhoto.FileName;
                db.Entry(league).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(league);
        }

        //
        // GET: /League/Delete/5

        public ActionResult Delete(int id = 0)
        {
            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return HttpNotFound();
            }
            return View(league);
        }

        //
        // POST: /League/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public ActionResult DeleteConfirmed(int id)
        {
            League league = db.Leagues.Find(id);
            db.Leagues.Remove(league);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kora Today/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kora_Today.Models;
using PagedList;
using PagedList.Mvc;
namespace Kora_Today.Controllers
{
    [Authorize(Roles="Admin")]
    public class MatchController : Controller
    {
        private KoraTodayEntities db = new KoraTodayEntities();

        //
        // GET: /Match/

        public ActionResult Index(int? page, string sortby)
        {
            ViewBag.league = string.IsNullOrEmpty(sortby) ? "league desc" : "";
            var matches = db.Matches.AsQueryable();
            switch(sortby)
            {
                case "league desc":
                    matches = matches.OrderByDescending(x => x.MatchLeague);
                    break;
                default:
                    matches = matches.OrderByDescending(x => x.MatchDate);
                    break;

            }
            return View(matches.ToPagedList(page ?? 1, 3));
        }

        //
        // GET: /Match/Create

        public ActionResult Create()
        {
            ViewBag.MatchLeague = new SelectList(db.Leagues, "LeagueName", "LeagueName");
            
            ViewBag.MatchHome = new SelectList(db.Clubs, "ClubName", "ClubName");
            ViewBag.MatchAway = new SelectList(db.Clubs, "ClubName", "ClubName");

            ViewBag.MatchHomeImage = new SelectList(db.Clubs, "ClubImage", "ClubImage");
            ViewBag.MatchAwayImage = new SelectList(db.Clubs, "ClubImage", "ClubImage");

            ViewBag.MatchStatus = new SelectList(new[]{"Live","Finished","Start Soon"});



            return View();
        }

        //
        // POST: /Match/Create

        [HttpPost]
        public ActionResult Create(Match match)
        {
            if (ModelState.IsValid)
            {
                db.Matches.Add(match);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MatchLeague = new SelectList(db.Leagues, "LeagueName", "LeagueName");

            ViewBag.MatchHome = new SelectList(db.Clubs, "ClubName", "ClubName");
            ViewBag.MatchAway = new SelectList(db.Clubs, "ClubName", "ClubName");

            ViewBag.MatchHomeImage = new SelectList(db.Clubs, "ClubImage", "ClubImage");
            ViewBag.MatchAwayImage = new SelectList(db.Clubs, "ClubImage", "ClubImage");

            ViewBag.MatchStatus = new SelectList(new[] { "Live", "Finished", "Start Soon" });


            return View(match);
        }

        //
        // GET: /Match/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        //
        // POST: /Match/Edit/5

        [HttpPost]
        public ActionResult Edit(Match match)
        {
            if (ModelState.IsValid)
            {
                db.Entry(match).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(match);
        }

        //
        // GET: /Match/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        //
        // POST: /Match/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Match match = db.Matches.Find(id);
            db.Matches.Remove(match);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kora Today/Views/Shared/_Dashboard.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<style>
    .navbar.navbar-inverse {
        background-color:lightseagreen;
        margin-top:11px;
        /*position:fixed;*/
    }
    .navbar.navbar-inverse .nav li a{
        color:black;
    }
</style>
<nav class="navbar navbar-inverse">
  <ul class="nav navbar-nav">
    <li>@Html.ActionLink("Leagues", "Index", "League")</li>
    <li>@Html.ActionLink("Clubs", "Index", "Club")</li>
    <li>@Html.ActionLink("News", "Index", "History")</li>
    <li>@Html.ActionLink("Matches", "Index", "Match")</li>
    <li>@Html.ActionLink("Match Details", "Index", "MatchDetail")</li>
    <li>@Html.ActionLink("Match TVs", "Index", "MatchTv")</li>
    <li>@Html.ActionLink("Slider", "Index", "Slider")</li>
    <li>@Html.ActionLink("Players", "Index", "Player")</li>
    <li>@Html.ActionLink("Assign Admin", "AssignRoleToUser", "Account")</li>
  </ul>
</nav>

Kora Today/Views/Shared/_FixturesPartial.cshtml
@model IEnumerable<Kora_Today.Models.Match>

@if (Model.Count() == 0)
{
    <h2 style="text-align:center;color:red;background-color:whitesmoke;">:: No Matches ::</h2> 
}

else
{
    foreach (var item in Model)
    {
                <table style="text-align:center;width:70%;margin:5px;">
            <tr style="color:red">
                <td><b>Watch Now @Html.ActionLink(" ", "MatchLive", new { id = item.MatchId }, new { @class = "fa fa-television" })</b></td>
                <td><b>Match Details @Html.ActionLink(" ", "MatchEvents", new { id = item.MatchId }, new { @class = "fa fa-bars" })</b></td>
            </tr>   
            </table>
                
               <table style="border: 2px solid black; width:70%;margin:10px;">
                    
                    <tr>
                        <td style="text-align:center"><b>@Html.DisplayFor(modelItem => item.MatchHome)</b></td>
                        <td style="text-align:center"></td>
                        <td style="text-align:center"><b>@Html.DisplayFor(modelItem => item.MatchAway)</b></td>
                        <td style="text-align:center"></td>

                    </tr>

                    <tr>
                        <td style="text-align:center"><img src="~/Uploads/@item.MatchHomeImage" style="width:50px;height:50px" /></td>
                        <td style="text-align:center"><b><span style="background-color:blue;border-radius:10px;color:white;padding:10px">@item.MatchResult</span></b></td>
                        <td style="text-align:center"><img src="~/Uploads/@item.MatchAwayImage" style="width:50px;height:50px" /></td>
                        @if (item.MatchStatus.Equals("Live"))
                        {<td style="text-align:center"><span style="background-color:red;border-radius:15px;color:white;padding:10px"><b>@item.MatchStatus</b></span></td>}
                        else if (item.MatchStatus.Equals("Finished"))
                        {<td style="text-align:center"><span style="background-color:black;border-radius:15px;color:white;padding:10px"><b>@item.MatchStatus</b></span></td>}
                        else
                        {<td style="text-align:center"><span style="background-color:lightgray;border-radius:15px;color:white;padding:10px"><b>@item.MatchStatus</b></span></td>}                    
                    </tr>
                    <tr>
                        <td style="text-align:center;color:green;"><b>Championship:</b></td>
                        <td style="text-align:center"></td>
                        <td style="text-align:center;color:green;"><b>Date:</b></td>
                        <td style="text-align:center;color:green;"><b>Time:</b></td>

                    </tr>

                    <tr>
                        <td  style="text-align:center;color:blue;">@Html.DisplayFor(modelItem => item.MatchLeague)</td>
                        <td style="text-align:center"></td>
                        <td  style="text-align:center;color:blue;">@Html.DisplayFor(modelItem => item.MatchDate)</td>
                        <td  style="text-align:center;color:blue;">@Html.DisplayFor(modelItem => item.MatchTime) CLT</td>

                    </tr>
               
                 </table>
    }
}

Kora Today/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Kora Today/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Kora Today/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Images/PG.ico" rel="icon" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

</head>


<body>
    
    <!-- Navar -->
    <nav>
        <div>
            <ul class="nav-ul-top">
                 <li style="float:left" >
                    <img src="~/Images/Kora-Today-Logo.jpg" style="width:150px ; height:50px ;  margin-left: 4px; margin-top: 4px;"   />
                </li>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Leagues", "LeagueHome", "Home")</li>
                <li>@Html.ActionLink("Fixtures", "FixturesCalendar", "Home")</li>
                <!-- Partial -->
                @Html.Partial("_LoginPartial")
               
            </ul>
        </div>
    </nav>
    <!-- Navar -->
   

<div class="container">
                @RenderBody()
</div>
            
    <!-- Footer -->
  <footer class="footer">
      
<a href="#" style="color:white;text-decoration: none;">Follow Us On : </a>
<a href="#" class="fa fa-facebook"></a>
<a href="#" class="fa fa-twitter"></a>
<a href="#" class="fa fa-youtube"></a>
<a href="#" class="fa fa-instagram"></a>

  </footer>
    <!-- Footer --> 
<section class="overlay">
<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>
</section>
</body>
</html>
<script>
    $(window).load(function () {
        $(".overlay, .overlay .spinner").fadeOut();
    });
</script>

Kora Today/Views/Shared/_Rankpartial.cshtml
@model IEnumerable<Kora_Today.Models.Club>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<table class="table">
    <tr>
        <th>
        </th>
        <th>
        </th>
        <th>
        </th>
        <th>
            @Html.DisplayName("MP")
        </th>
        <th>
            @Html.DisplayName("W")
        </th>
        <th>
            @Html.DisplayName("D")
        </th>
        <th>
            @Html.DisplayName("L")
        </th>
        <th>
            @Html.DisplayName("GF")
        </th>
        <th>
            @Html.DisplayName("GA")
        </th>
        <th>
            @Html.DisplayName("GD")
        </th>
        <th>
            @Html.DisplayName("Pts")
        </th>
        <th></th>
    </tr>
@{var x = 0;}
@foreach (var item in Model) {
    x++;
    <tr>
        <td>
            @x
        </td>
        <td>
           <img src="~/Uploads/@item.ClubImage" style="width:25px;height:25px">
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClubName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Played)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Won)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Drawn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GoalsFor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GoalsAgainst)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GoalsDifference)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Points)
        </td>
        <td></td>
    </tr>
    
}

</table>

Kora Today/Views/Shared/_TopSoccerpartial.cshtml
@model IEnumerable<Kora_Today.Models.Player>


<link href="~/Content/bootstrap.css" rel="stylesheet" />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Player Name")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Goals)
        </th>
        <th>
            @Html.DisplayName("Club")
        </th>
      </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Goals)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerClub)
        </td>
      </tr>
}

</table>