Kora Today/Models/History.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kora_Today.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryId { get; set; }
        public string HistoryTitle { get; set; }
        public string HistoryContent { get; set; }
        public string HistoryTime { get; set; }
        public string HistoryImage { get; set; }
        public int ClubId { get; set; }
    
        public virtual Club Club { get; set; }
    }
}

Kora Today/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kora_Today.Models;
using System.IO;

namespace Kora_Today.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HistoryController : Controller
    {
        private KoraTodayEntities db = new KoraTodayEntities();

        //
        // GET: /History/

        public ActionResult Index()
        {
            var histories = db.Histories.Include(h => h.Club);
            return View(histories.ToList());
        }

        //
        // GET: /History/Create

        public ActionResult Create()
        {
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName");
            return View();
        }

        //
        // POST: /History/Create

        [HttpPost]
        public ActionResult Create(History history, HttpPostedFileBase HistoryPhoto)
        {
            if (ModelState.IsValid)
            {

                string path = Path.Combine(Server.MapPath("~/Uploads"), HistoryPhoto.FileName);
                HistoryPhoto.SaveAs(path);
                history.HistoryImage = HistoryPhoto.FileName;
                history.HistoryTime = DateTime.Now.ToString();
                db.Histories.Add(history);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ModelState.Clear();
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName", history.ClubId);
            return View(history);
        }

        //
        // GET: /History/Edit/5

        public ActionResult Edit(int id = 0)
        {
            History history = db.Histories.Find(id);
            if (history == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName", history.ClubId);
            return View(history);
        }

        //
        // POST: /History/Edit/5

        [HttpPost]
        public ActionResult Edit(History history, HttpPostedFileBase HistoryPhoto)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), HistoryPhoto.FileName);
                HistoryPhoto.SaveAs(path);
                history.HistoryImage = HistoryPhoto.FileName;
                db.Entry(history).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClubId = new SelectList(db.Clubs, "ClubId", "ClubName", history.ClubId);
            return View(history);
        }

        //
        // GET: /History/Delete/5

        public ActionResult Delete(int id = 0)
        {
            History history = db.Histories.Find(id);
            if (history == null)
            {
                return HttpNotFound();
            }
            return View(history);
        }

        //
        // POST: /History/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            History history = db.Histories.Find(id);
            db.Histories.Remove(history);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kora Today/Views/History/Create.cshtml
@model Kora_Today.Models.History

@{
    ViewBag.Title = "Create News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create News</h2>

@using (Html.BeginForm("Create", "History", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>History</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HistoryTitle)
            @Html.ValidationMessageFor(model => model.HistoryTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryContent)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.HistoryContent)
            @Html.ValidationMessageFor(model => model.HistoryContent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryImage)
        </div>
        <div class="editor-field">
          <input id="HistoryPhoto" name="HistoryPhoto" type="file" />
            @Html.ValidationMessageFor(model => model.HistoryImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ClubId, "Club")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ClubId", String.Empty)
            @Html.ValidationMessageFor(model => model.ClubId)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Kora Today/Views/History/Delete.cshtml
@model Kora_Today.Models.History

@{
    ViewBag.Title = "Delete News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete News</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>History</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HistoryTitle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HistoryTitle)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HistoryContent)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HistoryContent)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HistoryTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HistoryTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HistoryImage)
    </div>
    <div class="display-field">
       <img src="~/Uploads/ @Html.DisplayFor(model => model.HistoryImage)" style="width:100px;height:100px" />
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Club.ClubName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Club.ClubName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Kora Today/Views/History/Edit.cshtml
@model Kora_Today.Models.History

@{
    ViewBag.Title = "Edit News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit News</h2>

@using (Html.BeginForm("Edit", "History", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>History</legend>

        @Html.HiddenFor(model => model.HistoryId)

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HistoryTitle)
            @Html.ValidationMessageFor(model => model.HistoryTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryContent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HistoryContent)
            @Html.ValidationMessageFor(model => model.HistoryContent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HistoryTime)
            @Html.ValidationMessageFor(model => model.HistoryTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HistoryImage)
        </div>
        <div class="editor-field">
          <input id="HistoryPhoto" name="HistoryPhoto" type="file" />
            @Html.ValidationMessageFor(model => model.HistoryImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ClubId, "Club")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ClubId", String.Empty)
            @Html.ValidationMessageFor(model => model.ClubId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Kora Today/Views/History/Index.cshtml
@model IEnumerable<Kora_Today.Models.History>
@RenderPage("/Views/Shared/_Dashboard.cshtml")

@{
    ViewBag.Title = "My News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">My News</h2>

<p style="text-align:center">
    @Html.ActionLink("Create News", "Create")
</p>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HistoryTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistoryContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistoryTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistoryImage)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HistoryTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HistoryContent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HistoryTime)
        </td>
        <td>
            <img src="~/Uploads/@item.HistoryImage" style="width:100px;height:100px" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.HistoryId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.HistoryId })
        </td>
    </tr>
}

</table>